import type { Metadata } from 'next';
import './globals.css';
import React from "react";
import Navigation from "@/components/custom/Navigation";
import {Inter} from "next/font/google"
import NavDrawer from "@/components/custom/NavDrawer";

const inter = Inter({ subsets: ['cyrillic', "latin"] })

export const metadata: Metadata = {
  title: "Комп'ютерний практикум",
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="uk">
      <body
        className={`${inter.className}`}
      >
        <Navigation/>
        <main className="flex flex-row w-full items-start">
          <div className="hidden lg:block">
            <NavDrawer/>
          </div>
          <div className="flex flex-col w-full">
            {children}
          </div>
        </main>
      </body>
    </html>
  );
}
